ER図追加、テーブル定義変更、TeamAPIのCROUD対応
rexiaxm7/practice-spring-boot-api pull request #12
Opened 2021-07-26 02:27 UTC by KazuyaNakagawa1029

2021-07-26 22:20 UTC, rexiaxm7 requested changes
指摘事項の対応お願いします！

ER図に関しての指摘は下記です。
#### 指摘①
userは必ずteamに所属し（userのteam_idがnot nullということはそういうことなので）
teamには0～n人所属するので、この関係はuser(0...n) - team (1)になります。
ER図はそのようになっていないので修正が必要です。
#### 指摘②
user - reportも同様に修正が必要です。
#### 指摘③
teamにはFKがないので修正が必要です。

DDLについての指摘は下記です。

#### 指摘④
docker-compose upの操作で想定通りのDBができ、APIですぐ動作確認できる必要があります。

2021-07-26 22:20 UTC, rexiaxm7 commented on docker/db/sql/00-report.sql
> +create table report
dockerでDB構築時に読み取られるSQLは名前順の想定です。
このファイル名ですとテーブルが存在せずにエラーを吐く可能性があるので見直しをお願いします。

2021-07-26 22:20 UTC, rexiaxm7 commented on docker/db/sql/00-user.sql
> +create table "user"
dockerでDB構築時に読み取られるSQLは名前順の想定です。
このファイル名ですとテーブルが存在せずにエラーを吐く可能性があるので見直しをお願いします。

2021-07-28 01:09 UTC, KazuyaNakagawa1029 commented on docker/db/sql/00-report.sql
> +create table report
対応しました。

2021-07-28 01:09 UTC, KazuyaNakagawa1029 commented on docker/db/sql/00-user.sql
> +create table "user"
対応しました。

2021-07-28 02:26 UTC, rexiaxm7 approved these changes
LGTM!

2021-07-28 02:38 UTC, merged