issue対応
rexiaxm7/practice-spring-boot-api pull request #16
Opened 2021-08-17 09:39 UTC by KazuyaNakagawa1029

2021-08-17 11:04 UTC, rexiaxm7 requested changes
コメント確認と修正お願いします！

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
>          incoming.text = "月報が提出されていません";
こちらもできれば、messages.propertiesで管理するようにしてください。

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +    @Scheduled(cron = "${BATCH_CRON}", zone = "${BATCH_TIMEZONE}")
application.propertiesは大文字でないことを失念していました。
他と合うような形式でapplication.propertiesの`BATCH_CRON`, `BATCH_TIMEZON`の命名を変更してください。

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +    private Optional<User> user;
こちらはどのような目的で使っていますか？
コードを見る限りでは不要のようなイメージがあります。確認お願いします！

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
渡す変数を引数の中で組み立てすぎるのは、可読性を落とすので変数化して渡してください。
個人的には３つくらいまでが許容範囲の印象です。

また、こちらはファイル名を容易に変更可能とするために
`{team_name}_{yyyy}_{mm}.md`のファイル名の元を環境変数に持たせて
使用箇所直前で{team_name}をチーム名で置換、{yyyy}をthisYearで置換、{mm}をthisMonthで置換すれば
`{team_name}_{yyyy}年{mm}.md`というファイル名に変更したい等の仕様変更も楽に対応できますので
そちらも検討してみてください。

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
渡す変数を引数の中で組み立てすぎるのは、可読性を落とすので変数化して渡してください。
個人的には３つくらいまでが許容範囲の印象です。

また、こちらはファイル名を容易に変更可能とするために
{team_name}_{yyyy}_{mm}.mdのファイル名の元を環境変数に持たせて
使用箇所直前で{team_name}をチーム名で置換、{yyyy}をthisYearで置換、{mm}をthisMonthで置換すれば
{team_name}_{yyyy}年{mm}.mdというファイル名に変更したい等の仕様変更も楽に対応できますので
そちらも検討してみてください。

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/bean/User.java
> +@Component
これも不要になりませんか？

2021-08-17 11:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        this.user = user;
これも不要となりませんか？

2021-08-18 04:31 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
>          incoming.text = "月報が提出されていません";
対応しました。

2021-08-18 04:31 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +    @Scheduled(cron = "${BATCH_CRON}", zone = "${BATCH_TIMEZONE}")
対応しました。

2021-08-18 04:32 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +    private Optional<User> user;
対応しました。

2021-08-18 04:32 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
対応しました。

2021-08-18 04:32 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
対応しました。

2021-08-18 04:32 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/bean/User.java
> +@Component
対応しました。

2021-08-18 04:32 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        this.user = user;
対応しました。

2021-08-18 05:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + msg.getMessage("file.name",new String[] { team.getName(),String.valueOf(thisYear),String.valueOf(thisMonth) }, Locale.JAPAN));
ファイル名に関しては、msgよりはapplication.propertiesに持たせた方良いと思います。
また、このように分割して可読性を向上させてみてください。

```suggestion
                    // createFileNameの中でapplication.propertiesに記載されたファイル名のテンプレートを元に
                    // 特定の文字列({team_name}等)を置換させて、生成する。
                    String fileName =  createFileName();
                    File file = new File( "src/main/resources/file/" + fileName);
```

2021-08-18 05:04 UTC, rexiaxm7 commented on src/main/resources/application.properties
> +batch.cron=0 * * * * *
この設定では秒実行されませんか？

2021-08-18 05:04 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
`file.name={0}_{1}年{2}月.md` で対応してくれていますが
{0}の表記は順番を変更できないため、英語圏等にある `{team_name}_{mm}_{yyyy}.md`のような形式に対応できなくなるので
自作の関数を作って`{team_name}`等の特定の文字列を置換するようにしてください。

2021-08-18 05:12 UTC, rexiaxm7 requested changes
修正した上で動作確認（データベース等も真っ新な状態でAPI経由でデータを登録し、バッチが動くまでを確認）お願いします。

2021-08-18 05:12 UTC, rexiaxm7 commented on src/main/resources/messages_ja.properties
> -NotBlank.Report.content=内容を入力してください
APIで必要となるメッセージだと思われますが、削除してしまって大丈夫ですか？

2021-08-18 05:36 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
>{0}の表記は順番を変更できないため
訂正です。順番は変更できますが、数字では入れ替えた時に対応している値がわかりづらくなりがちなので
上記仕様にするほうが良いです。

2021-08-18 07:36 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + team.getName() + thisYear + "年" + thisMonth + "月.md");
修正しました。

2021-08-18 07:37 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    File file = new File("src/main/resources/file/" + msg.getMessage("file.name",new String[] { team.getName(),String.valueOf(thisYear),String.valueOf(thisMonth) }, Locale.JAPAN));
修正しました。

2021-08-18 07:39 UTC, KazuyaNakagawa1029 commented on src/main/resources/application.properties
> +batch.cron=0 * * * * *
動きを確認するために変更していたのを戻し忘れておりました。
申し訳ございません。
修正しました。

2021-08-18 08:49 UTC, KazuyaNakagawa1029 commented on src/main/resources/messages_ja.properties
> -NotBlank.Report.content=内容を入力してください
ValidationMessages.propertiesに書き写した際に消し忘れていたものを今回削除したので
動き的には問題ございませんでした。

2021-08-18 22:15 UTC, rexiaxm7 requested changes
修正した上で動作確認お願いします！

2021-08-18 22:15 UTC, rexiaxm7 commented on build.gradle
> +
poiはexcel操作のためのライブラリなので、今回不要とならないでしょうか？

2021-08-18 22:15 UTC, rexiaxm7 commented on docker/db/sql/02-report.sql
> +    month   integer,
yearに関してはdefaultは不要としてください。
defaultを設定すると、insert時に項目を設定し忘れても動作してしまうため意図しない挙動・不具合につながります。

monthに関しては not null としてください。

2021-08-18 22:15 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    bw.close();
ここもメソッド抽出した方がよさそうです。

2021-08-18 22:15 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        }
前月について不具合がありそうです。
thisMonthが12になることはありそうでしょうか？（1月であれば、0となりそうですが…)

また1月に動いた際はthisYearは去年を指すので、命名的に良くなさそうです。
別の名前に変更してください。

2021-08-18 22:15 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    bw.close();
ここもメソッド抽出した方がよさそうです。
他と共通化できたりしませんか？

2021-08-18 22:15 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        }
システム的に不具合が発生しやすい箇所（日跨ぎ、月跨ぎ、年跨ぎ）で問題なさそうかどうかも
検討してみてください。

2021-08-18 22:15 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +            if (!checkSubmission(calendar, team)) {
こちらの内部では、今月提出されているか？の判定を行っているため
先月提出できていたか？の判定はできていないように思われます。どうでしょうか？

2021-08-19 08:17 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        }
申し訳ありません、不具合に気付いておりませんでした。
日付の取得方法をCalenderメソッドからLocalDateメソッドに変更することでこちらの不具合に対応しました。

2021-08-19 08:18 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    bw.close();
メソッド化しました。

2021-08-19 08:19 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +                    bw.close();
もう一つのファイルを作成するメソッドと共通化しました。

2021-08-19 08:21 UTC, KazuyaNakagawa1029 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +            if (!checkSubmission(calendar, team)) {
申し訳ありません、できておりませんでした。
内部で年と月を取得するのではなく年と月を引数として渡す形に変更しました。

2021-08-19 08:22 UTC, KazuyaNakagawa1029 commented on build.gradle
> +
扶養だったので削除しました。

2021-08-19 08:23 UTC, KazuyaNakagawa1029 commented on docker/db/sql/02-report.sql
> +    month   integer,
申し訳ありません、修正しました。

2021-08-19 11:13 UTC, rexiaxm7 requested changes
対応お願いします！

2021-08-19 11:13 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        LocalDate targetDate = LocalDate.of(2021,8,1).minusMonths(1);
テスト用のコードのままではありませんか？

2021-08-19 23:58 UTC, rexiaxm7 commented
batchが呼び出す処理をサービスに分割したほうがよさそうですね

2021-08-20 04:57 UTC, rexiaxm7 approved these changes
LGTM!

2021-08-20 04:58 UTC, rexiaxm7 commented on src/main/java/com/example/demo/batch/ReportBatch.java
> +        LocalDate targetDate = LocalDate.of(2021,8,1).minusMonths(1);
解消したことを確認済

2021-08-20 04:58 UTC, merged